[package]
name = "varve-core"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
description = "Runtime, codecs, and storage primitives for Varve binary formats"
documentation = "https://docs.rs/varve-core"

[features]
default = []
integrity = ["dep:crc32fast"]
mmap = ["dep:memmap2"]
zero-copy = ["mmap", "dep:zerocopy"]
compression-zstd = ["dep:zstd"]

[dependencies]
crc32fast = { workspace = true, optional = true }
memmap2 = { workspace = true, optional = true }
tempfile.workspace = true
thiserror.workspace = true
zerocopy = { workspace = true, optional = true, features = ["derive"] }
zstd = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_Threading"] }
